project_id = "lwhftiycpoaqldqubenw"

[functions.recognize-comic]
verify_jwt = false

[functions.search-comic]
verify_jwt = false

[functions.fetch-comic-cover]
verify_jwt = false

[functions.sync-gocollect]
verify_jwt = false

[functions.fetch-gocollect-value]
verify_jwt = false
